// For demo, allowed guesses and answers share one list. Swap this list in production.
export const WORDS = [
  'abide','about','above','abuse','adapt','adobe','adopt','adore','adult','after','again','agent','agile','agree','ahead',
  'aisle','alarm','album','alert','alike','alive','allow','alone','along','alter','amaze','amber','amend','amuse','angel',
  'anger','angle','angry','anime','ankle','apple','apply','apron','argue','arise','armor','array','arrow','aside','asset',
  'atlas','attic','audio','audit','avail','avoid','await','awake','award','aware','awful','axiom','bacon','badge','badly',
  'baker','balmy','banjo','barge','basic','basil','batch','bathe','beach','beard','begin','being','belly','bench','berry',
  'birth','black','blade','blame','blank','blast','blend','bless','blind','blink','block','blood','bloom','blown','bluer',
  'board','boast','bonus','boost','booth','bound','brain','brake','brand','brave','bread','break','brick','bride','brief',
  'bring','brisk','broad','broke','brown','brush','build','built','cabin','cable','camel','candy','canon','cargo','carol',
  'carry','carve','catch','cause','cease','chain','chair','chalk','champ','chant','chaos','charm','chart','chase','cheap',
  'check','cheek','cheer','chess','chest','chief','child','chili','chime','choir','chose','civil','claim','class','clean',
  'clear','clerk','click','cliff','climb','cling','clock','close','cloth','cloud','clown','coach','coast','color','comic',
  'coral','could','count','court','cover','crack','craft','crane','crash','crate','crazy','cream','creek','crest','crisp',
  'cross','crowd','crown','crude','crush','curve','daily','dance','dated','debut','debug','decay','decor','defer','delta',
  'dense','depot','depth','devil','diary','digit','diner','dirty','dizzy','dodge','doing','donor','doubt','dozen','draft',
  'drain','drama','drawn','dream','dress','drift','drink','drive','droid','drove','eager','eagle','early','earth','easel',
  'eaten','eerie','eight','elbow','elder','elect','elite','elope','email','embed','ember','enact','enemy','enjoy','enter',
  'entry','equal','equip','erase','error','ethic','evade','event','every','exact','exist','extra','fable','facet','faint',
  'fairy','faith','false','fancy','fatal','favor','feast','fence','fever','fiber','field','fiend','fifth','fight','final',
  'first','flame','flash','fleet','flesh','flick','flier','float','flock','flood','floor','flora','flour','fluid','flush',
  'focus','force','forge','forth','forty','forum','found','frame','fraud','fresh','fried','front','frost','fruit','fully',
  'funny','gauge','giant','given','glade','gland','glare','glass','glide','globe','glory','glove','glyph','grace','grade',
  'grain','grand','grant','grape','graph','grasp','grass','grave','great','green','greet','grief','grind','groom','group',
  'grove','guard','guest','guide','habit','happy','harsh','hasty','haunt','heart','heavy','hedge','hello','hence','hinge',
  'hobby','honey','honor','horse','hotel','house','human','humid','humor','hurry','ideal','image','imply','index','inner',
  'input','irony','issue','ivory','jelly','joint','judge','juice','juicy','kneel','knife','knock','known','label','labor',
  'laden','lager','laser','later','laugh','layer','learn','least','leave','legal','lemon','level','light','lilac','limit',
  'linen','liver','lobby','local','logic','loose','lunar','lunch','magic','major','maker','mango','maple','march','match',
  'maybe','mayor','medal','media','mercy','merge','merit','metal','meter','micro','might','miner','minor','model','money',
  'month','moral','motor','mount','mouse','mouth','movie','music','naive','nerve','never','newer','night','noble','noise',
  'north','novel','nurse','oasis','occur','ocean','offer','often','olive','onion','onset','opera','orbit','order','organ',
  'other','ought','outer','ovary','owner','paint','panel','panic','paper','party','pause','peace','pearl','penal','penny',
  'phase','phone','piano','piece','pilot','pitch','place','plain','plane','plant','plate','plead','pluck','plumb','point',
  'poker','polar','porch','pound','power','press','price','pride','prime','print','prior','prize','proof','proud','prove',
  'queen','query','quest','quick','quiet','quota','radar','radio','raise','rally','ranch','range','rapid','ratio','reach',
  'react','ready','realm','rebel','refer','relax','renew','reply','reset','rhyme','rider','ridge','right','rinse','rival',
  'river','roast','robot','rough','round','route','royal','ruler','rural','saint','salad','scale','scare','scene','scent',
  'scope','score','scout','screw','sense','serve','setup','shade','shaft','shake','shame','shape','share','shark','sheep',
  'shelf','shell','shift','shine','shirt','shock','shore','short','shout','shown','sight','since','skill','sleep','slice',
  'slide','slope','small','smart','smile','smoke','snack','snake','solid','solve','sorry','sound','south','space','spare',
  'spark','speak','speed','spend','spice','spike','spine','spite','split','spoke','sport','spray','squad','stack','staff',
  'stage','stain','stake','stand','stare','start','state','steam','steel','steep','steer','stick','still','stock','stone',
  'store','storm','story','stove','strap','straw','stuck','study','style','sugar','suite','sunny','super','swear','sweep',
  'sweet','swell','swept','swing','sword','table','taken','tasty','teach','tease','tempo','thank','their','theme','there',
  'thick','thing','think','third','those','three','throw','thumb','tiger','timer','tired','title','today','token','topic',
  'torch','total','touch','tower','toxic','trace','track','trade','trail','train','trait','trend','trial','tribe','trick',
  'troop','truck','truly','trunk','trust','truth','twice','under','union','unity','until','upper','upset','urban','usage',
  'usual','vague','valid','value','vapor','vault','venue','verse','video','vigor','vinyl','viral','vital','vivid','vocal',
  'voice','voter','wafer','wagon','waste','watch','water','weary','weigh','weird','whale','wheat','wheel','where','which',
  'while','white','whole','whose','woman','women','world','worry','worse','worst','worth','would','wound','wrath','write',
  'wrong','xenon','yearn','yeast','yield','young','youth','zebra','zesty','zonal'
] as const;

export const ANSWERS = WORDS;
export const ALLOWED_GUESSES = new Set(WORDS);
